[package]
name = "traiter"
description = "Traits collection."
license = "MIT"
version = "0.0.1-alpha"
edition = "2015"

[lib]
name = "traiter"

[features]
collections = []
numbers = []
std = []

[package.metadata.docs.rs]
all-features = true
