[package]
name = "traiter"
description = "Traits collection."
license = "MIT"
repository = "https://github.com/lycantropos/traiter"
version = "3.0.0-alpha"
edition = "2015"

[lib]
name = "traiter"

[features]
collections = []
numbers = []
std = []

[package.metadata.docs.rs]
all-features = true
